os:
    - windows
    - linux
    - osx
dist: xenial
language: rust
addons:
  apt:
    packages:
      - libusb-1.0-0-dev
script:
    - cargo build
    - cargo test
    - cargo test --no-default-features
